AS  = @echo -e "\033[0;33mASM" $< "\033[0m"; nasm
CC  = @echo -e "\033[0;34mCC " $< "\033[0m"; x86_64-elf-gcc
LD  =  echo -e "\033[1;36mLD " $@ "\033[0m"; x86_64-elf-gcc
CPP = @echo -e "\033[1;33mCPP" $< "\033[0m"; x86_64-elf-cpp
CP  = @echo -e "\033[0;32mCP " $(OBJ) $(OUT) "\033[0m"; cp
RM  = @echo -e "\033[0;31mRM " $(OBJ) "\033[0m"; rm
AR  = @echo -e "\033[0;31mAR " libc.a "\033[0m"; x86_64-elf-ar
